[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
address = "0.0.0.0"
port = 8080
maxMessageSize = 200
enableWebsocketCompression = true
maxUploadSize = 200
runOnSave = false

[browser]
gatherUsageStats = false
serverPort = 8501
serverAddress = "0.0.0.0"

[client]
toolbarMode = "minimal"
showErrorDetails = false

[runner]
fastReruns = true

[logger]
level = "info"
messageFormat = "%(asctime)s %(message)s"
